export interface Opportunity {
  id: string;
  title: string;
  organization: string;
  description: string;
  eligibility: string;
  deadline: string;
  country: string;
  state?: string;
  category: "Scholarships" | "Fellowships" | "Internships" | "Conferences" | "Hackathons" | "STEM Programs";
  applyLink: string;
  requiredDocuments: string[];
  field: string;
  incomeLimit?: number; // Maximum family income allowed
  degreeLevel?: string; // High School, Bachelor, Master, PhD
}

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: "Google Generation Scholarship (Women in Gaming)",
    organization: "Google",
    description: "Established to help aspiring computer scientists excel in technology and become leaders in the field. Selected students will receive funding for the upcoming academic year.",
    eligibility: "Identify as a female, pursuing a computer science or gaming degree at an accredited university.",
    deadline: "2026-09-30",
    country: "United States",
    category: "Scholarships",
    applyLink: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship/",
    requiredDocuments: ["Resume", "Academic Transcripts", "Two Letters of Recommendation", "Essay Responses"],
    field: "Computer Science",
    incomeLimit: 120000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-2",
    title: "Grace Hopper Celebration Fellowship",
    organization: "AnitaB.org",
    description: "The GHC Fellowship program provides scholarships for students and faculty to attend the world's largest gathering of women technologists.",
    eligibility: "Must be a student enrolled in an accredited degree program or faculty at a recognized college/university.",
    deadline: "2026-08-15",
    country: "United States",
    category: "Fellowships",
    applyLink: "https://ghc.anitab.org/",
    requiredDocuments: ["Proof of Enrollment / Employment", "Statement of Purpose", "CV"],
    field: "STEM",
    incomeLimit: 75000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-3",
    title: "Outreachy Open Source Internship",
    organization: "Outreachy",
    description: "Outreachy provides paid internships in open source to people who are subject to systemic bias or underrepresented in tech.",
    eligibility: "Internships are open to applicants internationally. Must be able to work 30 hours per week.",
    deadline: "2026-10-10",
    country: "Global",
    category: "Internships",
    applyLink: "https://www.outreachy.org/",
    requiredDocuments: ["Initial Application Essays", "Contribution Log"],
    field: "Software Engineering",
    incomeLimit: 50000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-4",
    title: "Women in Cybersecurity (WiCyS) Annual Conference Grant",
    organization: "WiCyS",
    description: "Scholarships to attend the WiCyS annual conference, providing opportunities for mentorship, networking, and career advancement.",
    eligibility: "Active WiCyS student member or professional trying to transition to cybersecurity.",
    deadline: "2026-11-01",
    country: "Canada",
    category: "Conferences",
    applyLink: "https://www.wicys.org/events/wicys-conference/",
    requiredDocuments: ["Member ID Proof", "Personal Statement", "Professional Resume"],
    field: "Cybersecurity",
    incomeLimit: 90000,
    degreeLevel: "Master",
  },
  {
    id: "opp-5",
    title: "SheHacks International Hackathon",
    organization: "Girls in Tech",
    description: "A 48-hour global virtual hackathon dedicated to creating digital solutions that address gender inequality and empower women.",
    eligibility: "Open to all women, non-binary individuals, and allies. Teams must consist of at least 50% female members.",
    deadline: "2026-07-30",
    country: "Global",
    category: "Hackathons",
    applyLink: "https://girlsintech.org/shehacks",
    requiredDocuments: ["Team Registration details", "GitHub link"],
    field: "Computer Science",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-6",
    title: "L'Oréal-UNESCO For Women in Science Fellowship",
    organization: "UNESCO / L'Oréal Foundation",
    description: "Supports outstanding female researchers in the life and physical sciences, granting substantial research funds to doctoral and post-doctoral candidates.",
    eligibility: "Female researchers pursuing doctoral or post-doctoral research in life, physical, engineering, or mathematics fields.",
    deadline: "2026-12-15",
    country: "France",
    category: "Fellowships",
    applyLink: "https://www.forwomeninscience.com/",
    requiredDocuments: ["Research Proposal", "Recommendation Letters", "PhD confirmation", "CV"],
    field: "STEM",
    degreeLevel: "PhD",
  },
  {
    id: "opp-7",
    title: "Adobe Research Women-in-Technology Scholarship",
    organization: "Adobe",
    description: "To bring more diversity to the tech industry, Adobe awards scholarships to female university students studying computer science.",
    eligibility: "Female undergraduate or master's student studying Computer Science, Computer Engineering, or related tech fields.",
    deadline: "2026-09-01",
    country: "Global",
    category: "Scholarships",
    applyLink: "https://research.adobe.com/scholarship/",
    requiredDocuments: ["Resume", "Transcripts", "Academic reference letter", "Creative submission (video/essay)"],
    field: "Computer Science",
    incomeLimit: 150000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-8",
    title: "Microsoft Women in STEM Internship",
    organization: "Microsoft",
    description: "A 12-week paid internship program at Microsoft focused on creating an inclusive environment for women pursuing careers in software engineering, product management, and data science.",
    eligibility: "Women enrolled in a Bachelor's or Master's program in Computer Science or related STEM fields. Strong academic record required.",
    deadline: "2026-08-31",
    country: "United States",
    state: "Washington",
    category: "Internships",
    applyLink: "https://careers.microsoft.com/",
    requiredDocuments: ["Resume", "Cover Letter", "Academic Transcripts", "Two Reference Letters"],
    field: "Software Engineering",
    incomeLimit: 200000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-9",
    title: "Girls Who Code Summer Immersion Program",
    organization: "Girls Who Code",
    description: "A free 2-week virtual or in-person immersive coding program that teaches girls with little to no coding experience about computer science.",
    eligibility: "Girls in 9th-11th grade (ages 14-17). No prior coding experience needed.",
    deadline: "2026-08-01",
    country: "United States",
    category: "STEM Programs",
    applyLink: "https://girlswhocode.com/programs/summer-immersion-program",
    requiredDocuments: ["Online Application Form", "Teacher Recommendation"],
    field: "Computer Science",
    incomeLimit: 80000,
    degreeLevel: "High School",
  },
  {
    id: "opp-10",
    title: "Amazon Women in Innovation Scholarship",
    organization: "Amazon",
    description: "Amazon's scholarship recognizes and supports driven women who are pursuing degrees in technology. Recipients receive a $10,000 scholarship and mentorship from Amazon engineers.",
    eligibility: "Self-identified women pursuing a Bachelor's or Master's in Computer Science, Electrical Engineering, or related field in the US or Canada.",
    deadline: "2026-10-31",
    country: "United States",
    category: "Scholarships",
    applyLink: "https://www.amazon.jobs/en/landing_pages/scholarships",
    requiredDocuments: ["Transcript", "Resume", "Short Answer Questions", "Letter of Recommendation"],
    field: "Computer Science",
    incomeLimit: 130000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-11",
    title: "Women Techmakers Scholars Program",
    organization: "Google",
    description: "Through the Women Techmakers Scholars Program, formerly the Google Anita Borg Memorial Scholarship Program, Google is furthering Dr. Anita Borg's vision of creating gender equality in the tech industry.",
    eligibility: "Female or non-binary student enrolled at a university in the US, Canada, or Europe, studying Computer Science, Computer Engineering, or a closely related technical field.",
    deadline: "2026-11-30",
    country: "United States",
    category: "Scholarships",
    applyLink: "https://buildyourfuture.withgoogle.com/scholarships/women-techmakers-scholars-program",
    requiredDocuments: ["Resume", "Transcript", "3 Essay Responses", "One Letter of Recommendation"],
    field: "Computer Science",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-12",
    title: "IEEE Women in Engineering International Leadership Conference",
    organization: "IEEE",
    description: "The IEEE Women in Engineering (WIE) International Leadership Conference is the largest international conference for women engineers and scientists.",
    eligibility: "Open to all IEEE members and non-members who identify as women or are allies, in engineering, technology, or related fields.",
    deadline: "2026-09-15",
    country: "Global",
    category: "Conferences",
    applyLink: "https://wie.ieee.org/events/",
    requiredDocuments: ["IEEE Membership Card or Application", "Short Motivation Letter"],
    field: "STEM",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-13",
    title: "Open Source Initiative (OSI) Women in Tech Grant",
    organization: "OSI",
    description: "A grant awarded to women actively contributing to open-source projects. Supports participation in open-source conferences and community events.",
    eligibility: "Women with a proven track record of contribution to at least one active open-source project. Must submit GitHub profile and contribution history.",
    deadline: "2026-07-15",
    country: "Global",
    category: "Fellowships",
    applyLink: "https://opensource.org/",
    requiredDocuments: ["GitHub Profile Link", "Contribution Summary", "Short Bio", "Budget Request"],
    field: "Software Engineering",
    incomeLimit: 60000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-14",
    title: "HerHack 2026 – Women's Hackathon Series",
    organization: "HerHack Foundation",
    description: "HerHack is a 24-hour hackathon exclusively for women and non-binary innovators to solve real-world challenges in healthcare, education, and sustainability.",
    eligibility: "Women and non-binary developers, designers, and data scientists globally. All skill levels are welcome.",
    deadline: "2026-10-20",
    country: "Global",
    category: "Hackathons",
    applyLink: "https://herhack.io",
    requiredDocuments: ["Registration Form", "Team formation or solo signup", "Brief project idea (optional)"],
    field: "Computer Science",
  },
  {
    id: "opp-15",
    title: "MIT PRIMES Circle – Women in Math Program",
    organization: "MIT",
    description: "PRIMES Circle is a free year-long math enrichment program for high school students in the Boston area, with a special focus on supporting young women in mathematics.",
    eligibility: "Female high school students in Grades 9-12 within commuting distance of MIT. Strong interest in mathematics required.",
    deadline: "2026-11-15",
    country: "United States",
    state: "Massachusetts",
    category: "STEM Programs",
    applyLink: "https://math.mit.edu/research/highschool/primes/circle/",
    requiredDocuments: ["Teacher Recommendation", "Academic Transcript", "Application Essay", "Math Problem Sets"],
    field: "Mathematics",
    degreeLevel: "High School",
  },
];
