export interface Opportunity {
  id: string;
  title: string;
  organization: string;
  description: string;
  eligibility: string;
  deadline: string;
  country: string;
  state?: string;
  category: "Scholarships" | "Fellowships" | "Internships" | "Conferences" | "Hackathons" | "STEM Programs" | "Research Programs" | "Exchange Programs";
  applyLink: string;
  requiredDocuments: string[];
  field: string;
  incomeLimit?: number;
  degreeLevel?: string;
}

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: "Google Generation Scholarship (Women in Gaming)",
    organization: "Google",
    description: "Established to help aspiring computer scientists excel in technology and become leaders in the field. Selected students will receive funding for the upcoming academic year.",
    eligibility: "Identify as a female, pursuing a computer science or gaming degree at an accredited university.",
    deadline: "2026-09-30",
    country: "United States",
    category: "Scholarships",
    applyLink: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship/",
    requiredDocuments: ["Resume", "Academic Transcripts", "Two Letters of Recommendation", "Essay Responses"],
    field: "Computer Science",
    incomeLimit: 120000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-2",
    title: "Grace Hopper Celebration Fellowship",
    organization: "AnitaB.org",
    description: "The GHC Fellowship program provides scholarships for students and faculty to attend the world's largest gathering of women technologists.",
    eligibility: "Must be a student enrolled in an accredited degree program or faculty at a recognized college/university.",
    deadline: "2026-08-15",
    country: "United States",
    category: "Fellowships",
    applyLink: "https://ghc.anitab.org/",
    requiredDocuments: ["Proof of Enrollment / Employment", "Statement of Purpose", "CV"],
    field: "STEM",
    incomeLimit: 75000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-3",
    title: "Outreachy Open Source Internship",
    organization: "Outreachy",
    description: "Outreachy provides paid internships in open source to people who are subject to systemic bias or underrepresented in tech.",
    eligibility: "Internships are open to applicants internationally. Must be able to work 30 hours per week.",
    deadline: "2026-10-10",
    country: "Global",
    category: "Internships",
    applyLink: "https://www.outreachy.org/",
    requiredDocuments: ["Initial Application Essays", "Contribution Log"],
    field: "Software Engineering",
    incomeLimit: 50000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-4",
    title: "Women in Cybersecurity (WiCyS) Annual Conference Grant",
    organization: "WiCyS",
    description: "Scholarships to attend the WiCyS annual conference, providing opportunities for mentorship, networking, and career advancement.",
    eligibility: "Active WiCyS student member or professional trying to transition to cybersecurity.",
    deadline: "2026-11-01",
    country: "Canada",
    category: "Conferences",
    applyLink: "https://www.wicys.org/events/wicys-conference/",
    requiredDocuments: ["Member ID Proof", "Personal Statement", "Professional Resume"],
    field: "Cybersecurity",
    incomeLimit: 90000,
    degreeLevel: "Master",
  },
  {
    id: "opp-5",
    title: "SheHacks International Hackathon",
    organization: "Girls in Tech",
    description: "A 48-hour global virtual hackathon dedicated to creating digital solutions that address gender inequality and empower women.",
    eligibility: "Open to all women, non-binary individuals, and allies. Teams must consist of at least 50% female members.",
    deadline: "2026-07-30",
    country: "Global",
    category: "Hackathons",
    applyLink: "https://girlsintech.org/shehacks",
    requiredDocuments: ["Team Registration details", "GitHub link"],
    field: "Computer Science",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-6",
    title: "L'Oréal-UNESCO For Women in Science Fellowship",
    organization: "UNESCO / L'Oréal Foundation",
    description: "Supports outstanding female researchers in the life and physical sciences, granting substantial research funds to doctoral and post-doctoral candidates.",
    eligibility: "Female researchers pursuing doctoral or post-doctoral research in life, physical, engineering, or mathematics fields.",
    deadline: "2026-12-15",
    country: "France",
    category: "Fellowships",
    applyLink: "https://www.forwomeninscience.com/",
    requiredDocuments: ["Research Proposal", "Recommendation Letters", "PhD confirmation", "CV"],
    field: "STEM",
    degreeLevel: "PhD",
  },
  {
    id: "opp-7",
    title: "Adobe Research Women-in-Technology Scholarship",
    organization: "Adobe",
    description: "To bring more diversity to the tech industry, Adobe awards scholarships to female university students studying computer science.",
    eligibility: "Female undergraduate or master's student studying Computer Science, Computer Engineering, or related tech fields.",
    deadline: "2026-09-01",
    country: "Global",
    category: "Scholarships",
    applyLink: "https://research.adobe.com/scholarship/",
    requiredDocuments: ["Resume", "Transcripts", "Academic reference letter", "Creative submission (video/essay)"],
    field: "Computer Science",
    incomeLimit: 150000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-8",
    title: "Microsoft Women in STEM Internship",
    organization: "Microsoft",
    description: "A 12-week paid internship program at Microsoft focused on creating an inclusive environment for women pursuing careers in software engineering, product management, and data science.",
    eligibility: "Women enrolled in a Bachelor's or Master's program in Computer Science or related STEM fields. Strong academic record required.",
    deadline: "2026-08-31",
    country: "United States",
    state: "Washington",
    category: "Internships",
    applyLink: "https://careers.microsoft.com/",
    requiredDocuments: ["Resume", "Cover Letter", "Academic Transcripts", "Two Reference Letters"],
    field: "Software Engineering",
    incomeLimit: 200000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-9",
    title: "Girls Who Code Summer Immersion Program",
    organization: "Girls Who Code",
    description: "A free 2-week virtual or in-person immersive coding program that teaches girls with little to no coding experience about computer science.",
    eligibility: "Girls in 9th-11th grade (ages 14-17). No prior coding experience needed.",
    deadline: "2026-08-01",
    country: "United States",
    category: "STEM Programs",
    applyLink: "https://girlswhocode.com/programs/summer-immersion-program",
    requiredDocuments: ["Online Application Form", "Teacher Recommendation"],
    field: "Computer Science",
    incomeLimit: 80000,
    degreeLevel: "High School",
  },
  {
    id: "opp-10",
    title: "Amazon Women in Innovation Scholarship",
    organization: "Amazon",
    description: "Amazon's scholarship recognizes and supports driven women who are pursuing degrees in technology. Recipients receive a $10,000 scholarship and mentorship from Amazon engineers.",
    eligibility: "Self-identified women pursuing a Bachelor's or Master's in Computer Science, Electrical Engineering, or related field in the US or Canada.",
    deadline: "2026-10-31",
    country: "United States",
    category: "Scholarships",
    applyLink: "https://www.amazon.jobs/en/landing_pages/scholarships",
    requiredDocuments: ["Transcript", "Resume", "Short Answer Questions", "Letter of Recommendation"],
    field: "Computer Science",
    incomeLimit: 130000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-11",
    title: "Women Techmakers Scholars Program",
    organization: "Google",
    description: "Through the Women Techmakers Scholars Program, formerly the Google Anita Borg Memorial Scholarship Program, Google is furthering Dr. Anita Borg's vision of creating gender equality in the tech industry.",
    eligibility: "Female or non-binary student enrolled at a university in the US, Canada, or Europe, studying Computer Science, Computer Engineering, or a closely related technical field.",
    deadline: "2026-11-30",
    country: "United States",
    category: "Scholarships",
    applyLink: "https://buildyourfuture.withgoogle.com/scholarships/women-techmakers-scholars-program",
    requiredDocuments: ["Resume", "Transcript", "3 Essay Responses", "One Letter of Recommendation"],
    field: "Computer Science",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-12",
    title: "IEEE Women in Engineering International Leadership Conference",
    organization: "IEEE",
    description: "The IEEE Women in Engineering (WIE) International Leadership Conference is the largest international conference for women engineers and scientists.",
    eligibility: "Open to all IEEE members and non-members who identify as women or are allies, in engineering, technology, or related fields.",
    deadline: "2026-09-15",
    country: "Global",
    category: "Conferences",
    applyLink: "https://wie.ieee.org/events/",
    requiredDocuments: ["IEEE Membership Card or Application", "Short Motivation Letter"],
    field: "STEM",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-13",
    title: "Open Source Initiative (OSI) Women in Tech Grant",
    organization: "OSI",
    description: "A grant awarded to women actively contributing to open-source projects. Supports participation in open-source conferences and community events.",
    eligibility: "Women with a proven track record of contribution to at least one active open-source project. Must submit GitHub profile and contribution history.",
    deadline: "2026-07-15",
    country: "Global",
    category: "Fellowships",
    applyLink: "https://opensource.org/",
    requiredDocuments: ["GitHub Profile Link", "Contribution Summary", "Short Bio", "Budget Request"],
    field: "Software Engineering",
    incomeLimit: 60000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-14",
    title: "HerHack 2026 – Women's Hackathon Series",
    organization: "HerHack Foundation",
    description: "HerHack is a 24-hour hackathon exclusively for women and non-binary innovators to solve real-world challenges in healthcare, education, and sustainability.",
    eligibility: "Women and non-binary developers, designers, and data scientists globally. All skill levels are welcome.",
    deadline: "2026-10-20",
    country: "Global",
    category: "Hackathons",
    applyLink: "https://herhack.io",
    requiredDocuments: ["Registration Form", "Team formation or solo signup", "Brief project idea (optional)"],
    field: "Computer Science",
  },
  {
    id: "opp-15",
    title: "MIT PRIMES Circle – Women in Math Program",
    organization: "MIT",
    description: "PRIMES Circle is a free year-long math enrichment program for high school students in the Boston area, with a special focus on supporting young women in mathematics.",
    eligibility: "Female high school students in Grades 9-12 within commuting distance of MIT. Strong interest in mathematics required.",
    deadline: "2026-11-15",
    country: "United States",
    state: "Massachusetts",
    category: "STEM Programs",
    applyLink: "https://math.mit.edu/research/highschool/primes/circle/",
    requiredDocuments: ["Teacher Recommendation", "Academic Transcript", "Application Essay", "Math Problem Sets"],
    field: "Mathematics",
    degreeLevel: "High School",
  },
  // ─── NEW: Research Programs ──────────────────────────────────────────────
  {
    id: "opp-16",
    title: "NSF Research Experiences for Undergraduates (REU)",
    organization: "National Science Foundation",
    description: "The REU program supports active research participation by undergraduate students in any of the areas of research funded by NSF, with priority for women and underrepresented minorities.",
    eligibility: "Undergraduate students enrolled in US colleges/universities. US citizens or permanent residents. Priority for women and underrepresented groups.",
    deadline: "2027-02-01",
    country: "United States",
    category: "Research Programs",
    applyLink: "https://www.nsf.gov/crssprgm/reu/",
    requiredDocuments: ["Research Statement", "Transcripts", "Two Reference Letters", "Personal Statement"],
    field: "STEM",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-17",
    title: "Wellcome Trust Research Fellowships for Women",
    organization: "Wellcome Trust",
    description: "Fellowships for outstanding female biomedical researchers to develop their research skills and establish themselves as independent researchers.",
    eligibility: "Female researchers with a PhD or MD and a strong publication record in biomedical sciences.",
    deadline: "2027-01-10",
    country: "United Kingdom",
    category: "Research Programs",
    applyLink: "https://wellcome.org/grant-funding/schemes/research-fellowships",
    requiredDocuments: ["Research Proposal", "CV", "Two Referees", "Host Institution Letter"],
    field: "Biomedical Sciences",
    degreeLevel: "PhD",
  },
  {
    id: "opp-18",
    title: "DAAD Research Internships in Science and Engineering (RISE)",
    organization: "DAAD",
    description: "RISE offers research internships at German universities and research institutes for undergraduate students from North America. Priority given to women in STEM.",
    eligibility: "Undergraduate students from North America in STEM fields. Minimum 2 years of undergraduate study completed.",
    deadline: "2026-12-01",
    country: "Germany",
    category: "Research Programs",
    applyLink: "https://www.daad.de/rise",
    requiredDocuments: ["Application Form", "Transcripts", "CV", "Language Proficiency Proof", "Motivation Letter"],
    field: "Engineering",
    degreeLevel: "Bachelor",
  },
  // ─── NEW: Exchange Programs ──────────────────────────────────────────────
  {
    id: "opp-19",
    title: "Fulbright U.S. Student Program",
    organization: "U.S. Department of State",
    description: "The Fulbright Program offers grants for US citizens to study, research, or teach abroad. Women in STEM fields are strongly encouraged to apply.",
    eligibility: "US citizen, bachelor's degree by start of grant. Open to all fields with strong preference for women in STEM.",
    deadline: "2026-10-12",
    country: "Global",
    category: "Exchange Programs",
    applyLink: "https://us.fulbrightonline.org/",
    requiredDocuments: ["Project Statement", "Personal Statement", "Transcripts", "Three Reference Letters", "Language Evaluation"],
    field: "STEM",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-20",
    title: "ERASMUS+ Study Exchange for Women in Tech",
    organization: "European Commission",
    description: "The Erasmus+ programme enables students to study at a partner university abroad, with special grants for women in computer science and engineering programs.",
    eligibility: "Enrolled at an Erasmus+ partner university. Women in CS, Engineering, or Data Science programs get priority grants.",
    deadline: "2027-03-15",
    country: "European Union",
    category: "Exchange Programs",
    applyLink: "https://erasmus-plus.ec.europa.eu/",
    requiredDocuments: ["Learning Agreement", "Transcript", "Language Certificate", "Motivation Letter"],
    field: "Computer Science",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-21",
    title: "Japan-IME Women in Science Exchange Program",
    organization: "Japan Science and Technology Agency",
    description: "A 6-month exchange program for women researchers to collaborate with Japanese universities and research institutes in STEM fields.",
    eligibility: "Female researchers with at least a Master's degree. Preference for AI, robotics, and materials science.",
    deadline: "2026-09-30",
    country: "Japan",
    category: "Exchange Programs",
    applyLink: "https://www.jst.go.jp/",
    requiredDocuments: ["Research Proposal", "CV", "Supervisor Letter", "Japanese Language Basics (N4+)"],
    field: "STEM",
    degreeLevel: "Master",
  },
  // ─── NEW: Additional Conferences ────────────────────────────────────────
  {
    id: "opp-22",
    title: "Women in Data Science (WiDS) Conference",
    organization: "Stanford University",
    description: "The annual Women in Data Science (WiDS) Conference at Stanford University features women doing outstanding work in data science across academia, industry, and government.",
    eligibility: "Open to all. Women practitioners, researchers, and students in data science, AI, and ML are particularly encouraged to submit.",
    deadline: "2026-11-01",
    country: "United States",
    category: "Conferences",
    applyLink: "https://www.widsconference.org/",
    requiredDocuments: ["Speaker Application Form", "Abstract (500 words)", "Short Bio"],
    field: "Data Science",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-23",
    title: "ACM-W Scholarship for Women in Computing",
    organization: "ACM",
    description: "The ACM-W scholarship supports women active in computer science and related fields to attend research conferences.",
    eligibility: "Women students enrolled full or part-time in a computing degree. Preference for those presenting at the conference.",
    deadline: "2026-08-15",
    country: "Global",
    category: "Conferences",
    applyLink: "https://women.acm.org/scholarships",
    requiredDocuments: ["Application Essay", "Advisor Letter", "Conference Acceptance Letter"],
    field: "Computer Science",
    degreeLevel: "Bachelor",
    incomeLimit: 100000,
  },
  // ─── NEW: Additional Hackathons ─────────────────────────────────────────
  {
    id: "opp-24",
    title: "MIT Reality Hack – Women's Track",
    organization: "MIT Media Lab",
    description: "A 5-day hackathon at MIT focused on immersive technologies (AR/VR/XR). Includes a dedicated women's innovation track with special mentorship.",
    eligibility: "Open globally to all skill levels. Women's track specifically for female and non-binary participants.",
    deadline: "2026-12-01",
    country: "United States",
    category: "Hackathons",
    applyLink: "https://www.mitrealityhack.com/",
    requiredDocuments: ["Application Form", "Portfolio or GitHub", "Team Preference"],
    field: "Technology",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-25",
    title: "NASA Space Apps Challenge – Women in Space Track",
    organization: "NASA",
    description: "An international hackathon to create apps and solutions using NASA's open data. Includes a Women in Space Science special category.",
    eligibility: "Open to all globally. No age or education restrictions. Individual or team participation.",
    deadline: "2026-09-01",
    country: "Global",
    category: "Hackathons",
    applyLink: "https://www.spaceappschallenge.org/",
    requiredDocuments: ["Team Registration", "Project Description"],
    field: "Space Science",
  },
  // ─── NEW: Additional Fellowships ────────────────────────────────────────
  {
    id: "opp-26",
    title: "Ford Foundation Fellowship Programs",
    organization: "Ford Foundation",
    description: "Fellowships for women and underrepresented minorities pursuing careers in higher education and research, particularly in social science and humanities.",
    eligibility: "Women and minority applicants pursuing doctoral or postdoctoral study in the US. Must be US citizen or national.",
    deadline: "2026-12-17",
    country: "United States",
    category: "Fellowships",
    applyLink: "https://www.nationalacademies.org/our-work/ford-foundation-fellowships",
    requiredDocuments: ["Research Proposal", "Transcripts", "Three Reference Letters", "Personal Statement"],
    field: "Social Sciences",
    degreeLevel: "PhD",
  },
  {
    id: "opp-27",
    title: "Hertz Fellowship for Women in Applied Science",
    organization: "Hertz Foundation",
    description: "The Hertz Fellowship supports bold graduate students in the applied physical, biological, and engineering sciences, with strong support for women applicants.",
    eligibility: "US citizens or permanent residents pursuing or planning to pursue a PhD in applied physical, biological, or engineering sciences.",
    deadline: "2026-10-27",
    country: "United States",
    category: "Fellowships",
    applyLink: "https://www.hertzfoundation.org/the-fellowship/",
    requiredDocuments: ["Application Form", "Transcripts", "Research Statement", "Three Reference Letters"],
    field: "Engineering",
    degreeLevel: "PhD",
  },
  {
    id: "opp-28",
    title: "Commonwealth Scholarship for Women in STEM",
    organization: "Commonwealth Scholarship Commission",
    description: "Fully funded scholarships for citizens of Commonwealth countries to pursue Master's or PhD degrees in STEM fields at UK universities, with priority for women.",
    eligibility: "Citizens of a Commonwealth country (except UK). Bachelor's degree with first-class honours. Women in STEM prioritised.",
    deadline: "2026-12-12",
    country: "United Kingdom",
    category: "Fellowships",
    applyLink: "https://cscuk.fcdo.gov.uk/scholarships/",
    requiredDocuments: ["Application Form", "Degree Certificates", "Research Proposal", "Two References", "English Proficiency"],
    field: "STEM",
    degreeLevel: "Master",
  },
  // ─── NEW: Additional Scholarships ───────────────────────────────────────
  {
    id: "opp-29",
    title: "P&G STEM Scholarship for Women",
    organization: "Procter & Gamble",
    description: "P&G awards scholarships to exceptional female students pursuing engineering and science degrees, pairing recipients with mentors from P&G's global network.",
    eligibility: "Female students in their first or second year of an engineering or science degree. GPA of 3.0 or higher required.",
    deadline: "2026-10-01",
    country: "Global",
    category: "Scholarships",
    applyLink: "https://www.pg.com/en_US/brands/scholarship.shtml",
    requiredDocuments: ["Resume", "Transcripts", "Two Reference Letters", "Essay (500 words)"],
    field: "Engineering",
    incomeLimit: 110000,
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-30",
    title: "Generation Google Scholarship for APAC",
    organization: "Google",
    description: "Supporting the next generation of computing leaders in the Asia Pacific region, with a specific focus on women pursuing degrees in computer science.",
    eligibility: "Female students enrolled full-time at a university in the APAC region, pursuing Computer Science or a related field.",
    deadline: "2026-12-01",
    country: "Global",
    category: "Scholarships",
    applyLink: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-apac",
    requiredDocuments: ["Resume", "Academic Transcripts", "Two Letters of Recommendation", "Essay Responses"],
    field: "Computer Science",
    degreeLevel: "Bachelor",
    incomeLimit: 80000,
  },
  // ─── NEW: STEM Programs ─────────────────────────────────────────────────
  {
    id: "opp-31",
    title: "Code2040 Fellows Program",
    organization: "Code2040",
    description: "A paid summer internship program placing Black and Latinx software engineering students at top tech companies, with a track dedicated to women engineers.",
    eligibility: "Black or Latinx students enrolled in a Bachelor's or Master's CS program. US students only. Women engineering track available.",
    deadline: "2026-10-15",
    country: "United States",
    category: "STEM Programs",
    applyLink: "https://www.code2040.org/fellows-program",
    requiredDocuments: ["Resume", "Personal Essay", "Technical Assessment", "Transcript"],
    field: "Software Engineering",
    degreeLevel: "Bachelor",
  },
  {
    id: "opp-32",
    title: "NASA Internship for Women in Aerospace",
    organization: "NASA",
    description: "A 10-week paid internship program at NASA for women pursuing degrees in aerospace engineering, astrophysics, or related STEM disciplines.",
    eligibility: "Female students enrolled in a STEM degree at a US accredited institution. US citizen or permanent resident. GPA 3.0+.",
    deadline: "2026-11-01",
    country: "United States",
    category: "STEM Programs",
    applyLink: "https://intern.nasa.gov/",
    requiredDocuments: ["Resume", "Transcripts", "Statement of Interest", "Faculty Recommendation"],
    field: "Aerospace Engineering",
    incomeLimit: 180000,
    degreeLevel: "Bachelor",
  },
];
